package com.wujie.android.voicedemo.ui

/**
 * Created by wujie on 2018/8/20/020.
 */
object BaiduASRDialogTheme {

    private const val MASK_CONTRAST_STYLE = -0x1000000
    private const val MASK_COLOR_STYLE = 0x00FFFFFF

    private const val LIGHT_CONTRAST_STYLE = 0x01000000
    private const val DEEP_CONTRAST_STYLE = 0x02000000

    private const val BLUE_COLOR_STYLE = 0x00000001
    private const val RED_COLOR_STYLE = 0x00000002
    private const val GREEN_COLOR_STYLE = 0x00000003
    private const val ORANGE_COLOR_STYLE = 0x00000004

    val THEME_BLUE_LIGHTBG = LIGHT_CONTRAST_STYLE or BLUE_COLOR_STYLE
    val THEME_BLUE_DEEPBG = DEEP_CONTRAST_STYLE or BLUE_COLOR_STYLE
    val THEME_RED_LIGHTBG = LIGHT_CONTRAST_STYLE or RED_COLOR_STYLE
    val THEME_RED_DEEPBG = DEEP_CONTRAST_STYLE or RED_COLOR_STYLE
    val THEME_GREEN_LIGHTBG = LIGHT_CONTRAST_STYLE or GREEN_COLOR_STYLE
    val THEME_GREEN_DEEPBG = DEEP_CONTRAST_STYLE or GREEN_COLOR_STYLE
    val THEME_ORANGE_LIGHTBG = LIGHT_CONTRAST_STYLE or ORANGE_COLOR_STYLE
    val THEME_ORANGE_DEEPBG = DEEP_CONTRAST_STYLE or ORANGE_COLOR_STYLE

    fun isDeepStyle(theme: Int): Boolean {
        return theme and MASK_CONTRAST_STYLE == DEEP_CONTRAST_STYLE
    }
}